const reverseReverse = (obj: object) => {
  const reversedObj = {};

  for (const key in obj) {
    reversedObj[obj[key]] = key;
  }

  return reversedObj;
};

export const setIdToSlug = {
  base5: "team-rocket",
  base4: "base-set-2",
  base3: "fossil",
  base2: "jungle",
  base1: "base",
  gym2: "gym-challenge",
  gym1: "gym-heroes",
  neo4: "neo-destiny",
  neo3: "neo-revelation",
  neo2: "neo-discovery",
  neo1: "neo-genesis",
  ecard3: "skyridge",
  ecard2: "aquapolis",
  ecard1: "expedition",
  ex16: "power-keepers",
  ex15: "dragon-frontiers",
  ex14: "crystal-guardians",
  ex13: "holon-phantoms",
  ex12: "legend-maker",
  ex11: "delta-species",
  ex10: "unseen-forces",
  ex9: "emerald",
  ex8: "deoxys",
  ex7: "team-rocket-returns",
  ex6: "firered-leafgreen",
  ex5: "hidden-legends",
  ex4: "team-magma-vs-team-aqua",
  ex3: "dragon",
  ex2: "sandstorm",
  ex1: "ruby-sapphire",
  dp7: "stormfront",
  dp6: "legends-awakened",
  dp5: "majestic-dawn",
  dp4: "great-encounters",
  dp3: "secret-wonders",
  dp2: "mysterious-treasures",
  dp1: "diamond-pearl",
  pl4: "arceus",
  pl3: "supreme-victors",
  pl2: "rising-rivals",
  pl1: "platinum",
  col1: "call-of-legends",
  hgss4: "hs-triumphant",
  hgss3: "hs-undaunted",
  hgss2: "hs-unleashed",
  hgss1: "heartgold-soulsilver",
  bw11: "legendary-treasures",
  bw10: "plasma-blast",
  bw9: "plasma-freeze",
  bw8: "plasma-storm",
  bw7: "boundaries-crossed",
  dv1: "dragon-vault",
  bw6: "dragons-exalted",
  bw5: "dark-explorers",
  bw4: "next-destinies",
  bw3: "noble-victories",
  bw2: "emerging-powers",
  bw1: "black-white",
  xy12: "evolutions",
  xy11: "steam-siege",
  xy10: "fates-collide",
  g1: "generations",
  xy9: "breakpoint",
  xy8: "breakthrough",
  xy7: "ancient-origins",
  xy6: "roaring-skies",
  dc1: "double-crisis",
  xy5: "primal-clash",
  xy4: "phantom-forces",
  xy3: "furious-fists",
  xy2: "flashfire",
  xy1: "xy",
  xy0: "kalos-starter-set",
  sm12: "cosmic-eclipse",
  sm115: "hidden-fates",
  sm11: "unified-minds",
  sm10: "unbroken-bonds",
  det1: "detective-pikachu",
  sm9: "team-up",
  sm8: "lost-thunder",
  sm75: "dragon-majesty",
  sm7: "celestial-storm",
  sm6: "forbidden-light",
  sm5: "ultra-prism",
  sm4: "crimson-invasion",
  sm35: "shining-legends",
  sm3: "burning-shadows",
  sm2: "guardians-rising",
  sm1: "sun-moon",
  swsh12pt5: "crown-zenith",
  swsh12: "silver-tempest",
  swsh11: "lost-origin",
  pgo: "pokemon-go",
  swsh10: "astral-radiance",
  swsh9: "brilliant-stars",
  swsh8: "fusion-strike",
  cel25: "celebrations",
  swsh7: "evolving-skies",
  swsh6: "chilling-reign",
  swsh5: "battle-styles",
  swsh45: "shining-fates",
  swsh4: "vivid-voltage",
  swsh35: "champion's-path",
  swsh3: "darkness-ablaze",
  swsh2: "rebel-clash",
  swsh1: "sword-shield",
  sv8: "surging-sparks",
  sv7: "stellar-crown",
  sv6pt5: "shrouded-fable",
  sv6: "twilight-masquerade",
  sv5: "temporal-forces",
  sv4pt5: "paldean-fates",
  sv4: "paradox-rift",
  sv3pt5: "151",
  sv3: "obsidian-flames",
  sv2: "paldea-evolved",
  sv1: "scarlet-violet",
};

export const setSlugToId = reverseReverse(setIdToSlug);

export const promosIdToSlug = {
  fut20: "futsal-collection",
  base6: "legendary-collection",
  si1: "southern-islands",
  bp: "best-of-game-promos",
  ru1: "pokemon-rumble-promos",
  // "set-promos": "black-star-promos"
  svp: "scarlet-violet-promos",
  swshp: "sword-shield-promos",
  smp: "sun-moon-promos",
  xyp: "x-y-promos",
  bwp: "black-white-promos",
  hsp: "heartgold-soulsilver-promos",
  dpp: "diamond-pearl-platinum-promos",
  np: "nintendo-black-star-promos",
  basep: "wotc-black-star-promos",
  // pop: "pop-series-promos",
  pop1: "pop-series-1",
  pop2: "pop-series-2",
  pop3: "pop-series-3",
  pop4: "pop-series-4",
  pop5: "pop-series-5",
  pop6: "pop-series-6",
  pop7: "pop-series-7",
  pop8: "pop-series-8",
  pop9: "pop-series-9",
  // mcdonalds: "mcdonalds-promos",
  mcd11: "mcdonalds-2011",
  mcd12: "mcdonalds-2012",
  mcd14: "mcdonalds-2014",
  mcd15: "mcdonalds-2015",
  mcd16: "mcdonalds-2016",
  mcd17: "mcdonalds-2017",
  mcd18: "mcdonalds-2018",
  mcd19: "mcdonalds-2019",
  mcd21: "mcdonalds-2021",
  mcd22: "mcdonalds-2022",
  // "ex-trainer-kits": "ex-trainer-kits",
  tk1a: "ex-trainer-kit-1a",
  tk1b: "ex-trainer-kit-1b",
  tk2a: "ex-trainer-kit-2a",
  tk2b: "ex-trainer-kit-2b",
};

export const promosSlugToId = reverseReverse(promosIdToSlug);

const allIds = {
  ...setIdToSlug,
  ...promosIdToSlug,
};

const allSlugs = {
  ...setSlugToId,
  ...promosSlugToId,
};

export const getSlugFromSetId = (id: string) => allIds[id] ?? "";

export const getSetIdFromSlug = (slug: string) => allSlugs[slug] ?? "";
